### ISSUE TITLE
keep reminder of previous message

### ISSUE THREAD

**Issue by rigorvzla** [jgravelle/GroqApiLibrary#10]
is it possible using this library, to be able to maintain a conversation and remember the previous messages, since whenever I call the method by sending a message, it is like starting a new conversation.

Could you help me with this problem. ?

**Comment by jgravelle** [comment]
Why, yes.  Yes I can.  See...  https://youtu.be/zm7H53vG5ns

**Comment by rigorvzla** [comment]
But i'm using dll in C# , please hice me examplenfor continue context conversation

**Comment by jgravelle** [comment]
I hear good things about this Dapper wrapper.  Plus, it's fun to say...
https://github.com/kevinhillinger/Dapper.Persistence
