### ISSUE TITLE
Streaming not working

### ISSUE THREAD

**Issue by emilmuller** [jgravelle/GroqApiLibrary#3]
Hey!

Streaming was not working. PostAsync seemed to wait for the entire response before continuing. This solved it:

```
          var requestMessage = new HttpRequestMessage(HttpMethod.Post, "https://api.groq.com/openai/v1/chat/completions")
          {
              Content = httpContent
          };

          // Configure to use streamed responses
          HttpResponseMessage response = await client.SendAsync(requestMessage, HttpCompletionOption.ResponseHeadersRead);
```

HttpCompletionOption.ResponseHeadersRead was the key.

Thanks for your library :)

**Comment by jgravelle** [comment]
Outstanding!

I'm a bit unclear on how your fix fits into GroqApiClient.cs.  If you could
show it in context I'll be happy to push the fix.

Thanks...!

-jjg
