### ISSUE TITLE
nuget package

### ISSUE THREAD

**Issue by robertovaldesperez** [jgravelle/GroqApiLibrary#5]
Is it possible to publish the project in nuget so that it can be downloaded? Is it compatible with net core 3.1?

**Comment by jgravelle** [comment]
Done!  Just search for 'Groq'...

**Comment by robertovaldesperez** [comment]
@jgravelle thanks a lot

**Comment by robertovaldesperez** [comment]
@jgravelle GroqApiLibrary is not compatible with netcoreapp 3.1

**Comment by jgravelle** [comment]
Try 'er now [v1.0.2] ...
