### ISSUE TITLE
It doesn't stream

### ISSUE THREAD

**Issue by mcapodici** [jgravelle/GroqApiLibrary#6]
I think you need to replace:

```
        using var response = await _httpClient.PostAsJsonAsync(BaseUrl, request);
        response.EnsureSuccessStatusCode();
```

With something like:

```
        StringContent httpContent = new(request.ToJsonString(), Encoding.UTF8, MediaTypeHeaderValue.Parse("application/json"));
        var requestMessage = new HttpRequestMessage(HttpMethod.Post, BaseUrl)
        {
            Content = httpContent
        };
        using var response = await client.SendAsync(requestMessage, HttpCompletionOption.ResponseHeadersRead);
```

I did this and got it to work on my machine.

Because SendAsync lets you return as soon as you get the headers, then process the stream after.

**Comment by jgravelle** [comment]
Try 'er now.  And thanks...

-jjg

**Comment by mcapodici** [comment]
I didn't get a chance to test it (as I am using an old version I just patched up, plus made local changes to), but thanks for fixing for future users.
