### ISSUE TITLE
Feature Request:Whisper support

### ISSUE THREAD

**Issue by AdaTomruk** [jgravelle/GroqApiLibrary#7]

**Comment by jgravelle** [comment]
Done!  Let me know how it works out for you...

**Comment by AdaTomruk** [comment]
Hello, this is unrelated to this topic, but I have a question.
I modified the code you wrote to work in unity c# (.net 2) and I want to share it on github, is it ok to share it as a fork of your project?

**Comment by jgravelle** [comment]
Absolutely!

I won't come after you 'til you get rich off it... 😎


-jjg
