### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by coltonchrane** [jgravelle/GroqApiLibrary#8]
Any plans to get this on nuget?

**Comment by coltonchrane** [comment]
Sorry should've checked the closed issues first

**Comment by coltonchrane** [comment]
So I went to pull this off nuget and got an error saying this package is incompatible with .Net 8.0 and appeared to because of a dependent package

**Comment by jgravelle** [comment]
On it.  Thanks...!

**Comment by coltonchrane** [comment]
@jgravelle Thank you. Your website is awesome btw!

**Comment by jgravelle** [comment]
I think you'll have more luck with the 1.0.8 version I just pushed.  It should work right outta the box.

Thanks...


-jjg
